Vagrant.configure("2") do |config|
  arch = `uname -m`.strip
  is_arm = arch == "arm64" || arch == "aarch64"
  config.vm.box = is_arm ? "bento/ubuntu-22.04" : "ubuntu/jammy64"

  # Compartir la raíz del proyecto (donde está docker-compose.yml)
  config.vm.synced_folder "../", "/vagrant"

  config.vm.define "manager" do |manager|
    manager.vm.hostname = "manager"
    manager.vm.network "private_network", ip: "192.168.56.10"
    manager.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    manager.vm.provision "shell", path: "setup-docker.sh"
  end

  config.vm.define "worker1" do |worker1|
    worker1.vm.hostname = "worker1"
    worker1.vm.network "private_network", ip: "192.168.56.11"
    worker1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    worker1.vm.provision "shell", path: "setup-docker.sh"
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.hostname = "worker2"
    worker2.vm.network "private_network", ip: "192.168.56.12"
    worker2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    worker2.vm.provision "shell", path: "setup-docker.sh"
  end
end
